core/views.py
from flask import render_template, request,Blueprint
from myproject.models import Zajezd
core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    zajezdy = Zajezd.query.order_by(Zajezd.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',zajezdy=zajezdy)

@core.route('/info')
def info():
    return render_template('info.html')

users/views.py
from myproject.users.forms import LoginForm, RegistrationForm, UpdateUserForm
from flask import Blueprint, render_template, redirect, url_for, flash,request
from flask_login import login_user,current_user, logout_user, login_required
from myproject import db
from myproject.models import User, Zajezd
from myproject.users.picture_handler import add_profile_pic
from werkzeug.security import generate_password_hash, check_password_hash


users = Blueprint('users',__name__)

@users.route('/logout')
def logout():
    logout_user()
    #built in function
    return redirect(url_for("core.index"))

@users.route('/register',methods=["GET","POST"])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data,
        password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Úspěšně jste se registrovali !')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

@users.route('/login',methods=["GET","POST"])
def login():

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                flash('Úspěšně jste se přihlásili !')

                next = request.args.get('next')

                if next == None or not next[0]=='/':
                    next=url_for('core.index')

                    return redirect(next)

    return render_template("login.html", form=form)

@users.route('/account',methods=["GET","POST"])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Účet byl aktualizován')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename="profile_pics/"+current_user.profile_image)

    return render_template('account.html', profile_image = profile_image, form=form)

@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    zajezdy = Zajezd.query.filter_by(author=user).order_by(Zajezd.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_zajezdy_posts.html',zajezdy=zajezdy,user=user)
    #když jdeš na jednotlivýho uživatele ukážete to přímo zájezdy od něj.

zajezdy/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint
from flask_login import current_user,login_required
from myproject import db
from myproject.models import Zajezd
from myproject.zajezdy.forms import ZajezdForm

zajezdy = Blueprint('zajezdy',__name__)

#create

@zajezdy.route("/create",methods=["GET","POST"])
@login_required
def create_post():
    form=ZajezdForm()

    if form.validate_on_submit():
        post = Zajezd(
        title=form.title.data,
        price=form.price.data,
        destination = form.destination.data,
        date_of_activity=form.date_of_activity.data,
        user_id=current_user.id
        )
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("core.index"))

    return render_template("create_post.html", form=form)

#view

@zajezdy.route('/<int:zajezd_id>')
def post(zajezd_id):
    zajezd = Zajezd.query.get_or_404(zajezd_id)
    return render_template('post.html',title=zajezd.title, date=zajezd.date,
    destination=zajezd.destination,price=zajezd.price,
    date_of_activity=zajezd.date_of_activity,post=zajezd)

#update
@zajezdy.route("/<int:zajezd_id>/update",methods=["GET","POST"])
@login_required
def update(zajezd_id):
    zajezd = Zajezd.query.get_or_404(zajezd_id)

    if zajezd.author != current_user:
        abort(403)
        #abort --> calls for error
    form = ZajezdForm()

    if form.validate_on_submit():

        zajezd.title = form.title.data
        zajezd.price = form.price.data
        zajezd.destination = form.destination.data
        zajezd.date_of_activity = form.date_of_activity.data

        db.session.commit()
        flash('Zajezd byl upraven!')
        return redirect(url_for('zajezdy.post',zajezd_id=zajezd.id))

    elif request.method == "GET":
        form.title.data = zajezd.title
        form.price.data = zajezd.price
        form.destination.data = zajezd.destination
        form.date_of_activity.data = zajezd.date_of_activity

    return render_template('create_post.html',title='Updating', form=form)

#delete
@zajezdy.route('/<int:zajezd_id>/delete',methods=["GET","POST"])
@login_required
def delete_post(zajezd_id):
    zajezd = Zajezd.query.get_or_404(zajezd_id)

    if zajezd.author != current_user:
        abort(403)

    db.session.delete(zajezd)
    db.session.commit()
    flash('Zájezd byl smazán !')
    return redirect(url_for('core.index'))

#view pro přihlašeného uživatele --> s kontaktem na vlastníka zájezdu
@zajezdy.route('/<int:zajezd_id>/show_contact')
@login_required
def view_email(zajezd_id):
    zajezd = Zajezd.query.get_or_404(zajezd_id)
    return render_template('view_post_with_email.html',title=zajezd.title, date=zajezd.date,
    destination=zajezd.destination,price=zajezd.price,date_of_activity=zajezd.date_of_activity,
    post=zajezd)

templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1>Vítejte {{current_user.username}}</h1>
    <img align = 'center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}" alt="Profile picture">

  </div>

</div>
<br>

<div class="jumbotron">
  <form method="POST" action="" enctype="multipart/form-data">
    {{form.hidden_tag() }}
    <div class="form-group">
    {{form.username.label(class='form-group')}} {{form.username(class='form-control') }}
    </div>
    <div class="form-group">
    {{form.email.label(class='form-group')}} {{form.email(class='form-control') }}
    </div>
    <div class="form-group">
    {{form.picture.label(class='form-group')}} {{form.picture(class='form-control') }}
    </div>
    <div class="form-group">
    {{form.submit(class='btn btn-primary') }}
    </div>

  </form>

  </div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Konečně dovolená</title>
    <link rel="stylesheet" href="{{url_for('static',filename="CSS/extras.css") }}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style>
body {
  background-image:url({{url_for('static',filename="background.jpg") }})}
                        }
</style>
  </head>
  <body>

<nav>


        <nav class="navbar sticky-top navbar navbar-dark bg-dark nav nav-pills nav-fill">
<!--
          <div class="navbar-nav">
-->

              <a class="nav-item nav-link active" href="{{ url_for('core.index') }}">Domů</a>


              <a class="nav-item nav-link" href="{{ url_for('core.info') }}">O nás</a>

              {% if current_user.is_authenticated %}

              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Účet</a>

              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

              <a class="nav-item nav-link" href="{{ url_for('zajezdy.create_post') }}">Přidat zájezd</a>

              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>

              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Registrace</a>

              <a class="nav-item nav link navbar-brand" href="#">
              <img src="{{url_for('static',filename="facebook.png")}}" width="30" height="30 "alt="facebook">
            </a>

            <a class="nav-item nav link navbar-brand "href="#">
              <img src="{{url_for('static',filename="instagram.png")}}" width="30" height="30" alt="instagram">
            </a>
              {% endif %}
            </ul>

            </div>

        </nav>
    <div class="fixed-bottom">...</div>

            {% block content %}




            {% endblock %}
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <div id="page-content">
              <div class="container text-center">
                <div class="row justify-content-center">
                  <div class="col-md-7">
                    <h1 class="font-weight-light mt-4 text-white">                         </h1>
                    <p class="lead text-white-50">                                                                                                </p>
                  </div>
                </div>
              </div>
            </div>
            <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
              <div class="container text-center">
                <small>Copyright Zbyněk Fiala &copy; zbynekfiala@gmail.com</small>
              </div>
            </footer>


  </body>
</html>

templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">


<div class="jumbotron">

<form class="form-group" method="POST">
  {{form.hidden_tag() }}
  <div class="form-group">
    {{form.title.label(class="form-control-label") }}
    {{form.title(class="form-control form-control-lg") }}
  </div>
    <div class="form-group">
    {{form.price.label(class="form-control-label") }}
    {{form.price(class="form-control form-control-lg") }}

    </div>
    <div class="form-group">
    {{form.destination.label(class="form-control-label") }}
    {{form.destination(class="form-control form-control-lg") }}

    </div>
    <div class="form-group">
    {{form.date_of_activity.label(class="form-control-label") }}
    {{form.date_of_activity(class="form-control form-control-lg") }}

    </div>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-info")}}

    </div>



</form>
</div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron" id="Heading">
  <div align="center">

<h1>Vítejte ve světě levnějšího cestování</h1>


</div>
</div>

<div class="container">
{% for post in zajezdy.items %}
<div class="card text-white bg-dark mb-3">
  <div class="card-body" id="Cards">
    <h2><a class="card-title"href="{{url_for('zajezdy.post',zajezd_id=post.id)}}">{{post.title}}</a></h2>
    <a href="{{url_for("users.user_posts",username=post.author.username) }}">Zveřejněno uživatelem: {{post.author.username}}</a>
    <p>Zveřejněno dne: {{post.date.strftime('%Y-%m-%d') }}</p>
    <a class="btn btn-primary"href="{{url_for('zajezdy.post',zajezd_id=post.id)}}">Zobrazit příspěvek</a>

  </div>
</div>

{% endfor %}

 <nav aria-label="Page navigation example">
   <ul class="pagination justify-content-center">
     {% for page_num in zajezdy.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if zajezdy.page == page_num %}
        <li class="page-item disabled">
          <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>

        {% else %}
          <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>

        {% endif %}

     {% endfor %}
  </nav>

{% endblock %}

templates/info.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <h1>O nás:</h1>
  <div class="container">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>

</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
<div class="container">
  <div class="jumbotron">
<h3>Přihlásit se:</h3>
    {# This hidden_tag is a CSRF security feature. #}
    <div class="form-group">


    {{ form.hidden_tag() }}
      </div>
    <div class="form-group">
    {{ form.email.label(class="form-group")}} {{ form.email(class="form-control") }}
      </div>
    <div class="form-group">
    {{ form.password.label(class="form-group") }} {{ form.password(class="form-control") }}
      </div>
    <div class="form-group">
    {{ form.submit(class="btn btn-outline-dark") }}
  </div>
  </div>

</div>

</form>
<br>
<br>
<br>
<br>
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block content %}
<div class="container">


<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Zveřejněno uživatelem: {{ post.author.username }}</h2>
  <h3>Dne: {{post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{ post.destination }}</p>
  <p>Termín konání je: {{ post.date_of_activity }}</p>
  <p>Za cenu: {{ post.price }} kč</p>
  <p>Pro zjištění kontaktu na uživatele se prosím přihlašte nebo registrujte</p>

{% if post.author == current_user %}
<div class="">
  <a class="btn btn-secondary" href="{{ url_for('zajezdy.update',zajezd_id=post.id) }}">Upravit</a>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Smazat</button>
</div>
{% endif %}
<br>
{% if current_user.is_authenticated and post.author != current_user %}
<a class="btn btn-secondary" href="{{ url_for('zajezdy.view_email',zajezd_id=post.id) }}">Zobrazit kontakt</a>
{% endif %}
</div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Smazat zájezd</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Jste si jistí, že chcete tento zájezd smazat?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zrušit</button>

        <form action="{{ url_for('zajezdy.delete_post', zajezd_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>








{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
  <div class="jumbotron">
<div class="container">


<h1>Registrace:</h1>
  <p>Ve formuláři níže se můžete na našich stránkách registrovat, což Vám nadále umožní přidávat Vaše vlastní zájezdy !</p>
  <div class="container">
    <div class="container">


  {{form.hidden_tag() }}
  </div>
  <div class="form-group">

  {{form.email.label(class='form-group')}} {{form.email(class='form-control') }}
  </div>
  <div class="form-group">

  {{form.username.label(class='form-group')}} {{form.username(class='form-control') }}
  </div>
  <div class="form-group">

  {{form.password.label(class='form-group')}} {{form.password(class='form-control') }}
  </div>
  <div class="form-group">

  {{form.password_confirm.label(class='form-group')}} {{form.password_confirm(class='form-control') }}
  </div>
  <div class="form-group">

  {{form.submit(class='btn btn-primary') }}
  </div>
</div>


</div>

  </div>
</form>


{% endblock %}

templates/user_zajezdy_posts.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <div class="jumbotron">
    <div align="center">
      <h1>Vítejte {{user.username}}</h1>
  <!-- IDEA: user je z user=user z views u zákazníka -->
  <img align="center" src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" alt="profilový obrázek">


    </div>

  </div>



{% for zajezd in zajezdy.items %}
    <h2><a href="{{url_for('zajezdy.zajezd',zajezd_id=zajezd.id) }}">{{zajezd.title}}</a></h2>
    nabídnuto: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{zajezd.author.username}}</a>
    <p class="text-muted">Dne: {{zajezd.date.strftime("%Y-%m-%d")}}</p>
    <br>
    <p>
    {{zajezd.price}}
    <br>
    {{zajezd.destination}}
    <br>
    {{zajezd.date_of_activity}}
    <br>
    </p>
{% endfor %}

</div>

<nav aria-label='Page Navigation example'>
  <ul class="pagination">
    {% for page_num in zajezdy.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
      {% if zajezdy.page == page_num %}
        <li class="page-item-disabled">
        <a class="page-link" href="{{url_for('users.user_zajezdy',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
      {% else %}
        <li class="page-item">
        <a class="page-link" href="{{url_for('users.user_zajezdy',username=user.username,page=page_num)}}">{{ page_num}}</a>
        </li>
      {% endif %}

    {% endfor %}
  </ul>

</nav>

{% endblock %}

templates/view_post_with_email.html
{% extends "base.html" %}
{% block content %}
<div class="container">


<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Zveřejněno uživatelem: {{ post.author.username }}</h2>
  <h3>Dne: {{post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{ post.destination }}</p>
  <p>Termín konání je: {{ post.date_of_activity }}</p>
  <p>Za cenu: {{ post.price }} kč</p>
  <p><strong>při zájmu můžete kontaktovat vlastníka na tento email: {{ post.author.email }}</strong></p>

{% if post.author == current_user %}
<div class="">
  <a class="btn btn-secondary" href="{{ url_for('zajezdy.update',zajezd_id=post.id) }}">Update</a>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
</div>
{% endif %}
</div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Smazat zájezd</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Jste si jistí, že chcete tento zájezd smazat?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zrušit</button>

        <form action="{{ url_for('zajezdy.delete_post', zajezd_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>








{% endblock %}